"""empty message

Revision ID: 1a7fc8b4fb48
Revises: 27d3d62873a7
Create Date: 2018-05-14 23:16:29.263250

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1a7fc8b4fb48'
down_revision = '27d3d62873a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('posts_tags',
    sa.Column('post_id', sa.String(length=45), nullable=True),
    sa.Column('tag_id', sa.String(length=45), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], )
    )
    op.drop_table('post2tags')
    op.add_column('tags', sa.Column('name', sa.String(length=60), nullable=True))
    op.drop_column('tags', 'tag')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tags', sa.Column('tag', mysql.VARCHAR(length=10), nullable=True))
    op.drop_column('tags', 'name')
    op.create_table('post2tags',
    sa.Column('post_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('tag_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('author_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('timestamp', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], name='post2tags_ibfk_1'),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], name='post2tags_ibfk_2'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], name='post2tags_ibfk_3'),
    sa.PrimaryKeyConstraint('post_id', 'tag_id', 'author_id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.drop_table('posts_tags')
    # ### end Alembic commands ###
