"""empty message

Revision ID: 27d3d62873a7
Revises: de69eace5a8a
Create Date: 2018-05-14 22:56:14.826123

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '27d3d62873a7'
down_revision = 'de69eace5a8a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post2tags',
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ),
    sa.PrimaryKeyConstraint('post_id', 'tag_id', 'author_id')
    )
    op.drop_constraint('tags_ibfk_1', 'tags', type_='foreignkey')
    op.drop_constraint('tags_ibfk_2', 'tags', type_='foreignkey')
    op.drop_column('tags', 'author_id')
    op.drop_column('tags', 'post_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tags', sa.Column('post_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('tags', sa.Column('author_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('tags_ibfk_2', 'tags', 'posts', ['post_id'], ['id'])
    op.create_foreign_key('tags_ibfk_1', 'tags', 'users', ['author_id'], ['id'])
    op.drop_table('post2tags')
    # ### end Alembic commands ###
